
import java.awt.Color;
import java.awt.FlowLayout;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author AlunoBCT
 */
public class PokeCardJFrame extends javax.swing.JFrame {

    /**
     * Creates new form PokeCardJFrame
     */
    public PokeCardJFrame(Pokemon p) {
        initComponents();
        
        labelNumero.setText("Nº " + p.getNumero().toString());
        labelNome.setText(p.getNome());
        labelTipo1.setText(p.getTipo1());
        labelTipo1.setOpaque(true);
        CorTipo(labelTipo1, p.getTipo1());
        labelTipo2.setText(p.getTipo2());
        labelTipo2.setOpaque(true);
        CorTipo(labelTipo2, p.getTipo2());
        textAreaDescricao.setText(p.getDescricao());
        textAreaDescricao.setWrapStyleWord(true);
        textAreaDescricao.setLineWrap(true);
        textAreaDescricao.setEditable(false);
        labelAltura.setText(p.getAltura().toString() + " m");
        labelPeso.setText(p.getPeso().toString() + " kg");
        labelHP.setText(p.getHp().toString());
        labelATK.setText(p.getAtk().toString());
        labelDEF.setText(p.getDef().toString());
        labelSPD.setText(p.getSpd().toString());
        labelCategoria.setText(p.getCategoria());
        labelImagem.setIcon(new ImageIcon(p.getUrl_imagem()));
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        setVisible(true);

    }

    void CorTipo(JLabel label, String s) {
        if (s != null) {
            label.setForeground(Color.white);
            switch (s) {
                case "Normal":
                    label.setBackground(Color.decode("#a8a878"));
                    break;
                case "Fire":
                    label.setBackground(Color.decode("#f08030"));
                    break;
                case "Fighting":
                    label.setBackground(Color.decode("#c03028"));
                    break;
                case "Water":
                    label.setBackground(Color.decode("#6890f0"));
                    break;
                case "Flying":
                    label.setBackground(Color.decode("#a890f0"));
                    break;
                case "Grass":
                    label.setBackground(Color.decode("#78c850"));
                    break;
                case "Poison":
                    label.setBackground(Color.decode("#a040a0"));
                    break;
                case "Electric":
                    label.setBackground(Color.decode("#f8d030"));
                    break;
                case "Ground":
                    label.setBackground(Color.decode("#e0c068"));
                    break;
                case "Psychic":
                    label.setBackground(Color.decode("#f85888"));
                    break;
                case "Rock":
                    label.setBackground(Color.decode("#b8a038"));
                    break;
                case "Ice":
                    label.setBackground(Color.decode("#98d8d8"));
                    break;
                case "Bug":
                    label.setBackground(Color.decode("#a8b820"));
                    break;
                case "Dragon":
                    label.setBackground(Color.decode("#7038f8"));
                    break;
                case "Ghost":
                    label.setBackground(Color.decode("#705898"));
                    break;
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        labelNome = new javax.swing.JLabel();
        labelImagem = new javax.swing.JLabel();
        labelNumero = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        labelAltura = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        labelPeso = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        labelHP = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        labelATK = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        labelDEF = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        labelSPD = new javax.swing.JLabel();
        labelTipo1 = new javax.swing.JLabel();
        labelTipo2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        labelCategoria = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaDescricao = new javax.swing.JTextArea();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelNome.setText("Nome");

        labelImagem.setText("jLabel2");

        labelNumero.setText("N");

        jLabel4.setText("Altura");

        labelAltura.setText("jLabel1");

        jLabel3.setText("Peso");

        labelPeso.setText("jLabel5");

        jLabel6.setText("HP");

        labelHP.setText("jLabel7");

        jLabel8.setText("Descrição");

        jLabel10.setText("ATK");

        labelATK.setText("jLabel11");

        jLabel12.setText("DEF");

        labelDEF.setText("jLabel13");

        jLabel14.setText("SPD");

        labelSPD.setText("jLabel15");

        labelTipo1.setText("Tipo1");

        labelTipo2.setText("Tipo2");

        jLabel5.setText("Categoria:");

        labelCategoria.setText("jLabel7");

        jLabel9.setText("Tipo:");

        textAreaDescricao.setColumns(20);
        textAreaDescricao.setRows(5);
        jScrollPane1.setViewportView(textAreaDescricao);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labelNome)
                                        .addGap(86, 86, 86))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(labelImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                        .addComponent(jLabel5)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel9)
                                                        .addGap(33, 33, 33)))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(labelCategoria)
                                                    .addComponent(labelTipo1))))
                                        .addGap(40, 40, 40)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(labelNumero)
                                            .addComponent(jLabel3)
                                            .addComponent(labelPeso)
                                            .addComponent(jLabel6)
                                            .addComponent(labelHP)
                                            .addComponent(jLabel4)
                                            .addComponent(labelAltura))
                                        .addGap(30, 30, 30)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(labelATK)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel12)
                                            .addComponent(labelDEF)
                                            .addComponent(jLabel14)
                                            .addComponent(labelSPD)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(labelTipo2)))))
                        .addGap(0, 23, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelNumero)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelAltura)
                            .addComponent(labelATK))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelPeso)
                            .addComponent(labelDEF))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelHP)
                            .addComponent(labelSPD))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(labelCategoria))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(labelTipo1)
                    .addComponent(labelTipo2))
                .addGap(44, 44, 44)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PokeCardJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PokeCardJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PokeCardJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PokeCardJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new PokeCardJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelATK;
    private javax.swing.JLabel labelAltura;
    private javax.swing.JLabel labelCategoria;
    private javax.swing.JLabel labelDEF;
    private javax.swing.JLabel labelHP;
    private javax.swing.JLabel labelImagem;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelNumero;
    private javax.swing.JLabel labelPeso;
    private javax.swing.JLabel labelSPD;
    private javax.swing.JLabel labelTipo1;
    private javax.swing.JLabel labelTipo2;
    private javax.swing.JTextArea textAreaDescricao;
    // End of variables declaration//GEN-END:variables
}
